module Main where

import Data.Aeson                 (eitherDecode)
import qualified Data.ByteString.Lazy as LB
import qualified Data.Text.IO         as TIO
import System.Environment         (getArgs)

import Anthropic.Client              (fromEnv)
import Anthropic.Messages            (sendMessage)
import Anthropic.Messages.Streaming  (streamMessage)
import Anthropic.Types

main :: IO ()
main = do
    args <- getArgs
    case args of
        ["--mock"]   -> runMock
        ["--stream"] -> runStream
        []           -> runLive
        _            -> putStrLn "Usage: examples [--mock | --stream]"

-- | Blocking request to the real Anthropic API.
runLive :: IO ()
runLive = do
    client <- fromEnv
    msg    <- sendMessage client req
    printMsg msg

-- | Streaming request to the real Anthropic API — prints tokens as they arrive.
runStream :: IO ()
runStream = do
    client <- fromEnv
    putStrLn "[streaming]"
    streamMessage client req $ \ev -> case ev of
        EvContentDelta _ (TextDelta t) -> TIO.putStr t
        EvMessageStop                  -> putStrLn ""
        _                              -> pure ()

-- | Replays a grievous-generated fixture. No API key needed.
--   Fixture generated by https://pypi.org/project/grievous-mcp/
runMock :: IO ()
runMock = do
    bs <- LB.readFile "test/fixtures/message_text.json"
    case eitherDecode bs of
        Left err  -> putStrLn $ "Failed to decode fixture: " <> err
        Right msg -> do
            putStrLn "[mock — powered by grievous-mcp]"
            printMsg msg

req :: MessageRequest
req = MessageRequest
    { reqModel         = claudeSonnet4
    , reqMessages      = [userMessage "Say hello in one sentence."]
    , reqMaxTokens     = 256
    , reqSystem        = Nothing
    , reqStopSequences = Nothing
    , reqTemperature   = Nothing
    , reqTools         = Nothing
    , reqToolChoice    = Nothing
    }

printMsg :: Message -> IO ()
printMsg msg = mapM_ print (msgContent msg)
