module Main where

import Data.Aeson                 (eitherDecode)
import qualified Data.ByteString.Lazy as LB
import System.Environment         (getArgs)

import Anthropic.Client   (fromEnv)
import Anthropic.Messages (sendMessage)
import Anthropic.Types

main :: IO ()
main = do
    args <- getArgs
    case args of
        ["--mock"] -> runMock
        []         -> runLive
        _          -> putStrLn "Usage: examples [--mock]"

-- | Live mode: calls the real Anthropic API. Requires ANTHROPIC_API_KEY.
runLive :: IO ()
runLive = do
    client <- fromEnv
    msg    <- sendMessage client req
    printMsg msg

-- | Mock mode: replays a grievous-generated fixture. No API key needed.
--   Fixture generated by https://pypi.org/project/grievous-mcp/
runMock :: IO ()
runMock = do
    bs <- LB.readFile "test/fixtures/message_text.json"
    case eitherDecode bs of
        Left err  -> putStrLn $ "Failed to decode fixture: " <> err
        Right msg -> do
            putStrLn "[mock — powered by grievous-mcp]"
            printMsg msg

req :: MessageRequest
req = MessageRequest
    { reqModel         = claude3_5Sonnet
    , reqMessages      = [userMessage "Say hello in one sentence."]
    , reqMaxTokens     = 256
    , reqSystem        = Nothing
    , reqStopSequences = Nothing
    , reqTemperature   = Nothing
    , reqTools         = Nothing
    , reqToolChoice    = Nothing
    }

printMsg :: Message -> IO ()
printMsg msg = mapM_ print (msgContent msg)
